const config = {
  backendApi: {
    baseUrl: 'https://api.newsexplo.gq',
    login: 'https://api.newsexplo.gq/signin',
    logout: 'https://api.newsexplo.gq/logout',
    signup: 'https://api.newsexplo.gq/signup',
    getUser: 'https://api.newsexplo.gq/users/me',
    articles: 'https://api.newsexplo.gq/articles',
  },
  newsApi: {
    apiKey: '9463a3af98f2474a93847c50157b49d3',
    newsUrl: 'https://newsapi.org/v2/everything?sortBy=popularity&apiKey=9463a3af98f2474a93847c50157b49d3&language=ru&pageSize=100',
  },
  elements: {
    status: {
      noscroll: 'noscroll',
      nodisplay: 'nodisplay',
      headerNavInactive: 'header__navigation_inactive',
      headerThemeDark: 'header_dark',
      headerThemeLight: 'header_light',
      headerHeadingDark: 'header__heading_dark',
      headerHeadingLight: 'header__heading_light',
      headerMenuDark: 'icon__hamburger_dark',
      headerMenuLight: 'icon__hamburger_light',
      buttonThemeDark: 'header__button_dark',
      buttonThemeLight: 'header__button_light',
      buttonIconDark: 'icon__logout_dark',
      buttonIconLight: 'icon__logout_light',
    },
    root: '.root',
    iconElement: '.icon',
    header: '.header',
    headerButton: '.header__button',
    headerMenu: '.header__menu',
    headerHeading: '.header__heading',
    headerItemSaved: '.header__item-saved',
    headerNavigation: '.header__navigation',
    popup: '.popup',
    popupSignup: '.popup__signup',
    popupLogin: '.popup__login',
    popupMessage: '.popup__message',
    popupCloseButton: '.popup__button_close',
    popupTitle: '.popup__title',
    popupForm: '.popup__form',
    popupFieldset: '.popup__fieldset',
    popupInput: '.popup__input',
    popupLabel: '.popup__label',
    popupError: '.popup__error',
    popupErrorEmail: '.popup__error_email',
    popupErrorUsername: '.popup__error_username',
    popupErrorPassword: '.popup__error_password',
    popupButtonSubmit: '.popup__button_submit',
    popupLink: '.popup__link',
  },
  params: {
    validPasswordMinLength: 8,
    validPasswordMaxLength: 30,
    validNameMinLength: 2,
    validNameMaxLength: 30,
  },
};

export default config;
